# Generated by Django 5.0.1 on 2025-12-14 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('bull_flag', 'Bull Flag'), ('bear_flag', 'Bear Flag'), ('head_shoulders', 'Head & Shoulders'), ('double_top', 'Double Top'), ('double_bottom', 'Double Bottom'), ('ascending_triangle', 'Ascending Triangle'), ('descending_triangle', 'Descending Triangle'), ('golden_cross', 'Golden Cross'), ('death_cross', 'Death Cross'), ('doji', 'Doji Star')], max_length=30)),
                ('timeframe', models.CharField(max_length=10)),
                ('confidence', models.IntegerField(default=0, help_text='Confidence percentage (0-100)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('success', 'Success'), ('failed', 'Failed')], default='active', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_patterns', to='dashboard.asset')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='PatternAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('pattern', 'Pattern Detected'), ('breakout', 'Breakout'), ('reversal', 'Reversal'), ('rsi', 'RSI Signal'), ('volume', 'Volume Spike')], max_length=20)),
                ('message', models.TextField()),
                ('confidence', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.asset')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patterns.detectedpattern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatternHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Accuracy percentage', max_digits=5, null=True)),
                ('timestamp', models.DateTimeField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patterns.detectedpattern')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
