# Generated by Django 5.0.1 on 2025-12-14 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_horizon_days', models.IntegerField(default=7)),
                ('risk_tolerance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('predicted_high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('predicted_low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('confidence_score', models.IntegerField(default=0, help_text='Confidence percentage (0-100)')),
                ('rsi_divergence', models.BooleanField(default=False)),
                ('macd_crossover', models.BooleanField(default=False)),
                ('sentiment_analysis', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='dashboard.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('bull_flag', 'Bull Flag'), ('bear_flag', 'Bear Flag'), ('head_shoulders', 'Head & Shoulders'), ('double_top', 'Double Top'), ('double_bottom', 'Double Bottom'), ('ascending_triangle', 'Ascending Triangle'), ('descending_triangle', 'Descending Triangle'), ('golden_cross', 'Golden Cross'), ('death_cross', 'Death Cross'), ('doji', 'Doji Star')], max_length=30)),
                ('timeframe', models.CharField(help_text='e.g., 15m, 1H, 4H, 1D', max_length=10)),
                ('match_percentage', models.IntegerField(default=0, help_text='Pattern match percentage (0-100)')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='dashboard.asset')),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='forecast.forecast')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('confidence_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('confidence_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecast.forecast')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('forecast', 'date')},
            },
        ),
    ]
